### PR TITLE
Restore Pool Shares section

### LINKED ISSUE #1042: Restore pool shares section

### LINKED ISSUE #1144: Highest liquidity section fails if one subgraph is down
the whole section fails if one subgraph is down. It should be just ignore and fetch data from other ones

### LINKED ISSUE #1145: Profile stats fail if one subgraph is down
Screenshot from 2022-02-25 14-51-42

### LINKED ISSUE #1157: Pool transaction tab in profile shows incorrect infos
**Describe the bug**
In the pool transaction tab in the profile section only title (but the link it points to is broken) and time seem to be correct, data set field is empty, network is always unknown.

**Screenshots**
Screenshot 2022-03-03 at 16 04 29

### LINKED ISSUE #1166: Unified representation of value in pools/profile
Currently we still have a mix of liquidity and tvl 
image
image

We need to be consistent and the data to make sense . Also when you add/remove liquidity you see liquidity

image

So i have a tvl of 1090 but when i remove i can remove 67% ~ 579 ocean , 100% ~ 874 ocean (rough calculation, not accurate)

Also we need to validate these numbers
This is more of a discussion issue. I'll handle the changes in the pool shares pr

### PR DESCRIPTION
**Pull request by claudiaHash**
- fixes #1042
- fixes #1144 
- fixes #1145
- fixes #1166
- fixes #1157 

Changes proposed in this PR:

- restore pool shares section tab in profile history, highest liquidity section and profile stats, fixes and refactors all around

### CODE REVIEW

**Comment by mihaisc** [comment]
If you have selected network where the subgraph is offline the tab never loads. If i select just the network with online subgraph and refresh it works.
image

File: src/@context/Profile.tsx [hunk 1]
```diff
@@ -141,6 +141,7 @@ function ProfileProvider({
           poolShares
         )
       } catch (error) {
+        setIsPoolSharesLoading(false)
```
Comment (kremalicious) [inline src/@context/Profile.tsx:144]: theoretically™, the `finally` is reached on both, success and `catch`ed error so `setIsPoolSharesLoading(false)` should fire in any case. But I guess this is one of those weirdnesses you encountered? But if not we could remove that extra `setIsPoolSharesLoading(false)` here

File: src/@utils/accessDetailsAndPricing.ts [hunk 2]
```diff
@@ -308,22 +308,26 @@ export async function getAccessDetails(
...
+    )
 
-  const tokenPrice: TokenPrice = tokenQueryResult.data.token
-  const accessDetails = getAccessDetailsFromTokenPrice(tokenPrice, timeout)
-  return accessDetails
+    const tokenPrice: TokenPrice = tokenQueryResult.data.token
+    const accessDetails = getAccessDetailsFromTokenPrice(tokenPrice, timeout)
+    return accessDetails
+  } catch (error) {
+    LoggerInstance.log('Error getting access details: ', error.message)
```
Comment (kremalicious) [inline src/@utils/accessDetailsAndPricing.ts:329]:
```suggestion
    LoggerInstance.error('Error getting access details: ', error.message)
```

File: src/@utils/accessDetailsAndPricing.ts [hunk 3]
```diff
@@ -333,43 +337,48 @@ export async function getAccessDetailsForAssets(
...
+        )
 
-      currentAsset.accessDetails = accessDetails
-    })
+        currentAsset.accessDetails = accessDetails
+      })
+    }
+    return assetsExtended
+  } catch (error) {
+    LoggerInstance.log('Error getting access details: ', error.message)
```
Comment (kremalicious) [inline src/@utils/accessDetailsAndPricing.ts:382]:
```suggestion
    LoggerInstance.error('Error getting access details: ', error.message)
```

File: src/@utils/aquarius.ts [hunk 4]
```diff
@@ -170,6 +170,28 @@ export async function getAssetsFromDidList(
   }
 }
 
+export async function getAssetsFromDtList(
+  dtList: string[],
+  chainIds: number[],
+  cancelToken: CancelToken
+): Promise<any> {
```
Comment (kremalicious) [inline src/@utils/aquarius.ts:177]: we should be able to be more precise here on the return type instead of `any`

File: src/@utils/ocean.ts [hunk 5]
```diff
@@ -4,22 +4,27 @@ import { AbiItem } from 'web3-utils/types'
...
+        network === 'moonbeamalpha' ||
+        network === 1287 ||
+        network === 'bsc' ||
+        network === 56 ||
+        network === 'gaiaxtestnet' ||
+        network === 2021000
+        ? undefined
+        : process.env.NEXT_PUBLIC_INFURA_PROJECT_ID
+    ) as Config
+    // TODO: remove hack once address is fixed
```
Comment (kremalicious) [inline src/@utils/ocean.ts:20]: puh, can't remember why this hack is there. Most likely can be removed as the `oceanTokenAddress` should come from ocean.js now?

File: src/@utils/ocean.ts [hunk 6]
```diff
@@ -4,22 +4,27 @@ import { AbiItem } from 'web3-utils/types'
...
+    if (network === 'rinkeby' || network === 4)
+      config.oceanTokenAddress = '0x8967bcf84170c91b0d24d4302c2376283b0b3a07'
+    return config as Config
+  } catch (error) {
+    LoggerInstance.log('Error getting ocean config: ', error.message)
```
Comment (kremalicious) [inline src/@utils/ocean.ts:25]:
```suggestion
    LoggerInstance.error('Error getting ocean config: ', error.message)
```

File: src/@utils/ocean.ts (hunk 5 above)
Comment (mihaisc) [reply src/@utils/ocean.ts:20]: this is my hack from like 2 months ago :))

File: src/@context/Profile.tsx (hunk 1 above)
Comment (claudiaHash) [reply src/@context/Profile.tsx:144]: yes, u're right. I'l fix it in a moment

File: src/@utils/subgraph.ts [hunk 7]
```diff
@@ -388,17 +415,21 @@ export async function getPoolSharesData(
...
+      chainIds
+    )
+    for (let i = 0; i < result.length; i++) {
+      result[i].poolShares.forEach((poolShare: PoolShare) => {
+        data.push(poolShare)
+      })
+    }
+    return data
+  } catch (error) {
+    console.error('Error fetchData: ', error.message)
```
Comment (kremalicious) [inline src/@utils/subgraph.ts:431]:
```suggestion
    LoggerInstance.error('Error fetchData: ', error.message)
```

File: src/@utils/subgraph.ts [hunk 8]
```diff
@@ -223,10 +244,15 @@ export async function fetchData(
 ): Promise<any> {
   try {
     const client = getUrqlClientInstance()
+    const checkUrl = await verifyUrl(context.url)
```
Comment (kremalicious) [inline src/@utils/subgraph.ts]: not sure about this although it's a nice simple trick. Just concerned that this doubles the requests we make.

When `client.query` does a request, and that errors, that is essentially a URL check so might be worth rather looking into what exactly to react to from the urql response. They have [whole page on error handling](https://formidable.com/open-source/urql/docs/basics/errors/) and somehow they will return a bunch of errors when encountered: https://formidable.com/open-source/urql/docs/api/core/#combinederror. Which should be part of the `OperationResult` we are receiving: https://formidable.com/open-source/urql/docs/api/core/#operationresult

So this might be a more reliable way of detecting subgraph errors. There are also ways to add more what they call [Exchanges](https://formidable.com/open-source/urql/docs/architecture/#the-exchanges), one of them is [errorExchange](https://formidable.com/open-source/urql/docs/api/core/#errorexchange).

That all might take longer to check out and figure out, so if we're in a hurry currently seems to work, but it comes with a heavy price of double the requests.

File: src/@utils/ocean.ts (hunk 6 above)
Comment (kremalicious) [reply src/@utils/ocean.ts:25]: or, that whole `try/catch` in here might be overkill as we are simple reading values from a json and if we don't find anything method just returns `null`. So almost sure the `try/catch` here would never be used

File: src/@utils/subgraph.ts (hunk 8 above)
Comment (kremalicious) [reply src/@utils/subgraph.ts]: nice, fixed with [76db8b9](https://github.com/oceanprotocol/market/pull/1139/commits/76db8b9464dfd6fa31f82308e68fc41c87b44dce) while I was writing this

File: src/@utils/subgraph.ts [hunk 9]
```diff
@@ -200,20 +201,40 @@ const OpcFeesQuery = gql`
   }
 `
 
+async function verifyUrl(url: string): Promise<number> {
```
Comment (kremalicious) [inline src/@utils/subgraph.ts:204]: we can now remove this method

File: src/@utils/subgraph.ts [hunk 10]
```diff
@@ -200,20 +201,40 @@ const OpcFeesQuery = gql`
...
+}
+
 export function getSubgraphUri(chainId: number): string {
-  const config = getOceanConfig(chainId)
-  return config.subgraphUri
+  try {
+    const config = getOceanConfig(chainId)
+    return config.subgraphUri
+  } catch (error) {
+    LoggerInstance.log('Get ocean config error: ', error.message)
```
[the remark this answers is not in the document]
Comment (kremalicious) [reply src/@utils/subgraph.ts:222]: same here [as above](https://github.com/oceanprotocol/market/pull/1139/files#r818687915)

File: src/@utils/subgraph.ts [hunk 11]
```diff
@@ -200,20 +201,40 @@ const OpcFeesQuery = gql`
...
+    }
+  }
+}
+
 export function getSubgraphUri(chainId: number): string {
-  const config = getOceanConfig(chainId)
-  return config.subgraphUri
+  try {
+    const config = getOceanConfig(chainId)
+    return config.subgraphUri
```
Comment (kremalicious) [inline src/@utils/subgraph.ts:220]: if we do this here as `return config?.subgraphUri` then again no need for `try/catch` as the only error here could be that `subgraphUri` can't be accessed from undefined `config`, and the `?` prevents that from erroring

File: src/@utils/subgraph.ts [hunk 12]
```diff
@@ -237,21 +259,22 @@ export async function fetchDataForMultipleChains(
...
-    const context: OperationContext = {
-      url: `${getSubgraphUri(
-        chainId
-      )}/subgraphs/name/oceanprotocol/ocean-subgraph`,
-      requestPolicy: 'network-only'
-    }
-    try {
+  try {
+    for (const chainId of chainIds) {
+      const context: OperationContext = {
```
Comment (kremalicious) [inline src/@utils/subgraph.ts:264]: shouldn't we use `getQueryContext()` helper from above here too?

File: src/components/Profile/History/PoolShares.tsx [hunk 13]
```diff
@@ -174,6 +170,7 @@ export default function PoolShares({
         )
         setAssets(assets)
       } catch (error) {
+        setLoading(false)
```
Comment (kremalicious) [inline src/components/Profile/History/PoolShares.tsx:173]: same as above: https://github.com/oceanprotocol/market/pull/1139/files#r818637638

File: src/components/Profile/History/PoolShares.tsx [hunk 14]
```diff
@@ -174,6 +170,7 @@ export default function PoolShares({
...
         console.error('Error fetching pool shares: ', error.message)
```
Comment (kremalicious) [inline src/components/Profile/History/PoolShares.tsx:174]: while we're at it:

```suggestion
        LoggerInstance.error('Error fetching pool shares: ', error.message)
```

File: src/@utils/aquarius.ts (hunk 4 above)
Comment (mihaisc) [reply src/@utils/aquarius.ts]: not sure we can, this is the result from elasticsearch. It's kinda complicated and not worth mapping now.  I created an issue at some point to see if we can handle some light mapping of es types but it gets complicated and not worth it.

Comment (claudiaHash) [reply src/@utils/aquarius.ts]: I mapped it to Asset[ ]. since we don't use accessDetails in this case I think it's enough

**Comment by kremalicious** [comment]
Now UI, output of liquidity should be exactly like we do it on the pool tab where we do not output the datatoken. This is what I get on my pool shares:

Screen Shot 2022-03-03 at 14 45 40

File: src/@utils/subgraph.ts [hunk 15]
```diff
@@ -237,21 +242,17 @@ export async function fetchDataForMultipleChains(
...
       const response = await fetchData(query, variables, context)
-      datas = datas.concat(response.data)
-    } catch (error) {
-      console.error('Error fetchData: ', error.message)
+      if (!response || response.error) continue
+      datas = datas.concat(response?.data)
     }
+    return datas
+  } catch (error) {
+    LoggerInstance.error('Error fetchData: ', error.message)
```
Comment (kremalicious) [inline src/@utils/subgraph.ts:254]: for debugging really helps to be precise in those messages for these generic methods, doesn't help if all of them say they come from `fetchData`. So this here should say `Error fetchDataForMultipleChains`.

File: src/@utils/subgraph.ts [hunk 16]
```diff
@@ -268,7 +269,7 @@ export async function getOpcFees(chainId: number) {
     )
     opcFees = response?.data?.opc
   } catch (error) {
-    console.error('Error fetchData: ', error.message)
+    LoggerInstance.error('Error fetchData: ', error.message)
```
Comment (kremalicious) [inline src/@utils/subgraph.ts:272]: and this one `Error getOpcFees`

File: src/@utils/subgraph.ts [hunk 17]
```diff
@@ -388,17 +389,21 @@ export async function getPoolSharesData(
...
+      chainIds
+    )
+    for (let i = 0; i < result.length; i++) {
+      result[i].poolShares.forEach((poolShare: PoolShare) => {
+        data.push(poolShare)
+      })
+    }
+    return data
+  } catch (error) {
+    LoggerInstance.error('Error fetchData: ', error.message)
```
Comment (kremalicious) [inline src/@utils/subgraph.ts:405]: and this one `Error getPoolSharesData`

**Comment by claudiaHash** [comment]
> Each time i swap tabs/change networks i get different numbers 

Yes, I encountered the same issue, still on it

**Comment by kremalicious** [comment]
somewhere we have way too many refetches, like when I deselect a network while pool shares tab is open, it looks like 2 rounds of fetches happen shortly after another. This is also visible in the above posted screen recording

**Comment by mihaisc** [comment]
I'll hop on this pr, the whole `Profile` component is acting weird, hope we won't need big refactor

**Comment by kremalicious** [comment]
Current state, picked up on what was in here, think all the errors are gone and I also made sure to unify the calculations between what we do on asset's pool tab and here in the pool shares table. So far, so good but one major problem I can't find the exact reason yet. Basically the numbers are correct, but they are on the wrong asset, here the below asset should display 15 OCEAN and the top one 11 OCEAN

Screen Shot 2022-03-07 at 14 07 11

Somewhere in `getAssetsFromPoolShares()` matching `ddoList` with `assetList` seem to not work out correctly, investigating...

**Comment by claudiaHash** [comment]
I'm checking it out too

**Comment by mihaisc** [comment]
The numbers look good. We can do a lot of optimizations at a later time. Currently if i uncheck/check another network we refetch everything and it's slow.
image

**Comment by kremalicious** [comment]
> Currently if i uncheck/check another network we refetch everything and it's slow.

yes, whenever `chainIds` changes all subgraphs are hit again to get the new `poolShares` in the `Profile` provider. Which then triggers various effects in subcomponents to recalculate. Only using some delta between previous selected `chainIds` and newly selected ones, and then only hit those subgraphs could be a first effective optimization

**Review by kremalicious — APPROVED** [review]
good enough™ and has lots of changes already so we should run with it and test in daily development. Thanks @claudiaHash & @mihaisc, there was something for everybody in here :-)
