### PR TITLE
Fix broken explorer links for multinetwork

### LINKED ISSUE #759: Explorer links are broken
All uses of `ExplorerLink` seem broken on asset details:

- metadata history
- user profile link
- pool link
- datatoken link

### PR DESCRIPTION
**Pull request by KatunaNorbert**
Fixes #759 .

Changes proposed in this PR:
Fix explorerLinks for:
- metadata history
- user profile link
- pool link
- datatoken link

### CODE REVIEW

File: src/components/organisms/AssetActions/Pool/index.tsx [hunk 1]
```diff
@@ -278,15 +278,15 @@ export default function Pool(): ReactElement {
...
                 path={`address/${price?.address}`}
               >
                 Pool
               </ExplorerLink>
               <ExplorerLink
-                networkId={networkId}
+                networkId={ddo.chainId}
                 path={
-                  networkId === 137 || networkId === 1287
+                  ddo.chainId === 137 || ddo.chainId === 1287
```
Comment (kremalicious) [inline src/components/organisms/AssetActions/Pool/index.tsx:289]: forgot about this check. We recently switched Polygon to use `polygonscan.com` as explorer in ocean.js ConfigHelper, which behaves just like etherscan. So we can remove the check for `137` as it's now `token` there too, e.g. https://polygonscan.com/token/0x282d8efce846a88b159800bd4130ad77443fa1a1

In fact all explorer links we now have in ConfigHelper behave like etherscan, but still 2 left we need as check: `1287` & `2021000`

**Comment by jamiehewitt15** [comment]
Just tested this out and the links seem to be working now

**Comment by bogdanfazakas** [comment]
Functionality wise looks good, handle the requested change from Matthias and it should be good to go

File: src/components/organisms/AssetActions/Pool/index.tsx (hunk 1 above)
Comment (KatunaNorbert) [reply src/components/organisms/AssetActions/Pool/index.tsx:289]: Right, I checked Polygon and Mainnet and no need for check. Not sure what `2021000` is

Comment (kremalicious) [reply src/components/organisms/AssetActions/Pool/index.tsx:289]: I have this file bookmarked just for that cause I never can remember chainIds :-) https://github.com/oceanprotocol/ocean.js/blob/main/src/utils/ConfigHelper.ts

`2021000` is Gaia-X testnet but so far we are not dealing with it but we can still add the check for it here as its expected this will always stay blockscout-based explorer so will need `/tokens/` here

Comment (KatunaNorbert) [reply src/components/organisms/AssetActions/Pool/index.tsx]: Cool, thanks

**Review by kremalicious — APPROVED** [review]
perfect, I think we found all possible explorer combinations, thanks for picking this up so quickly
