### PR TITLE
Fixing metadata history

### LINKED ISSUE #773: History links not working for some assets
Some metadata history links are not working , tx is undefined

examples: https://market.oceanprotocol.com/asset/did:op:b98B96B2DDe7e1237928400cFCD54327eF58fff4

https://market.oceanprotocol.com/asset/did:op:7FBEDfF92F39ae900393B17370E192D508458FDB

### PR DESCRIPTION
**Pull request by jamiehewitt15**
Closes #773 
Supersedes #784

Changes proposed in this PR:

- Getting chainId from DDO

### CODE REVIEW

File: src/helpers/wrapRootElement.tsx [hunk 1]
```diff
@@ -11,7 +11,7 @@ export default function wrapRootElement({
 }): ReactElement {
   return (
     <Web3Provider>
-      <UrqlProvider>
```
Comment (jamiehewitt15) [inline src/helpers/wrapRootElement.tsx:14]: I tried removing `UrqlProvider` from here but that causes some errors

**Comment by kremalicious** [comment]
What we need to prevent is to have multiple providers nested on one screen. Did lots of tinkering and I think the best way is to always pass a specific query context, and have the provider only there to have an initial client as that's required.

So something like this in the `EditHistory` component:

```js
const queryContext = getQueryContext(ddo?.chainId)
const [result] = useQuery({
  query: getReceipts,
  variables: { address: ddo?.dataToken.toLowerCase() },
  context: queryContext,
  pause: !ddo || !queryContext
})
```

 Currently going this direction and trying to get the asset details screen to render again

**Comment by kremalicious** [comment]
Should work now™. My above code sample actually worked but not many ways to instruct `useQuery` to stop rendering as I could not get that `pause` functionality to stop re-rendering the component, but this would be pattern to use:

```js
const [queryContext, setQueryContext] = useState<OperationContext>()

useEffect(() => {
  if (!ddo) return
  const queryContext = getQueryContext(ddo.chainId)
  setQueryContext(queryContext)
}, [ddo])

const [result] = useQuery({
  query: getReceipts,
  variables: { address: ddo?.dataToken.toLowerCase() },
  context: queryContext,
  pause: !ddo || !queryContext
})
const { data } = result
```

**Review by kremalicious — APPROVED** [review]

**Review by mihaisc — APPROVED** [review]
