### PR TITLE
restore order for assets with fixed pricing

### LINKED ISSUE #1356: Price is never calculated - Cannot read properties of undefined (reading 'baseToken')
**Describe the bug**
There are a couple of assets where the price isn't calculated. It is just endlessly loading....

**To Reproduce**
1. Go to [this asset](https://v4.market.oceanprotocol.com/asset/did:op:8edc467bce44355de5b6ee7a860f6d463cf494bbba3420a64e4f3038522d3ccb) and see that the price is never loaded.
2. Go to [this asset](https://v4.market.oceanprotocol.com/asset/did:op:b0d9ea2a46172d9425228d4bcef696536d44583af98f44e7610ebe3c0d02be81) and see that the price is never loaded.

**Expected behavior**
There should be a price and it should be possible to buy the dataset.

**Screenshots**

Price never loads - 2022-04-25_13-27

**Logs**

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'baseToken')
    at 629-8534c0ba3d0887c7.js:1:32271
    at s (main-914fbfab4f90b52f.js:1:89133)
    at Generator._invoke (main-914fbfab4f90b52f.js:1:88921)
    at Generator.P.forEach.e.<computed> [as next] (main-914fbfab4f90b52f.js:1:89556)
    at xt (629-8534c0ba3d0887c7.js:1:29419)
    at i (629-8534c0ba3d0887c7.js:1:29623)
    at 629-8534c0ba3d0887c7.js:1:29684
    at new Promise (<anonymous>)
    at 629-8534c0ba3d0887c7.js:1:29563
    at o (629-8534c0ba3d0887c7.js:1:32593)
```

### LINKED ISSUE #1363: Buy doesn't work for assets published with a fixed price of 1 Ocean
Steps to reproduce:
1. Publish an asset using a fixed price schema and a price of 1 Ocean
2. Try to buy it
3. A "Failed to buy datatoken from pool" error shows up

https://v4.market.oceanprotocol.com/asset/did:op:3958da6ccc5439d48888d8b98c960444f0d1832b95e5ef20af899f03b5758be4 

Screenshot 2022-04-27 at 12 49 00

### LINKED ISSUE #1364: Download not working for Free assets
**Describe the bug**
There is an issue when trying to purchase Free assets. After clicking the "Get" button and signing the transactions, the asset isn't downloaded. The "Get" button remains in place and isn't replaced by the download button

**To Reproduce**
1. Purchase an asset
2. Notice that it isn;t downloaded

**Screen recording**

https://user-images.githubusercontent.com/20739535/165502878-f31f4056-c2e2-4b20-83de-059cb3aa0d42.mp4

### PR DESCRIPTION
**Pull request by EnzoVezzaro**
- Fixes #1356 .
- Fixes #1364 
- Fixes #1363 

Changes proposed in this PR:

- restore order for fixed pricing
- restore download button after purchase
- disable download/buy button if the user is on network different as the asset's

### CODE REVIEW

**Review by kremalicious — APPROVED** [review]
good find. I see more weird things in that effect but will handle in #1357 like the loading spinner always being restarted whenever any of the dependency like `poolData` changes

**Comment by EnzoVezzaro** [comment]
> #1357

yes, most probably for #1357 it's enough checking [these deps](https://github.com/oceanprotocol/market/blob/fix/issue-1356-loader-stuck-button-asset/src/components/Asset/AssetActions/Download.tsx#L90:L90) or just comment/remove these [2 lines](https://github.com/oceanprotocol/market/blob/fix/issue-1356-loader-stuck-button-asset/src/components/Asset/AssetActions/Download.tsx#L67-L68) - tried it, it works, but it's not the most clean solution.

I found another bug thought. Fixed assets are having issues when trying to buy. 

Screen Shot 2022-04-26 at 6 23 53 AM

**Comment by kremalicious** [comment]
> but it's not the most clean solution.

yup, I would question putting a price loading spinner on the button in the first place, should be on the price as that's what's loading but not sure yet about best solution.

And that looks like a bug indeed, would be great to add this in a new issue unless you can quickly solve it in here with some optional chaining

**Comment by EnzoVezzaro** [comment]
> 

Nope, this seems to be related to a query that is returning no information about the pool. Without this information the `order` call fails, it happens only for the `fixed` price asset. This bug actually made me go back to check my solution, and I found that this is what was actually causing the issue with the loader. I will continue solving the issue on this PR

**Comment by alexcos20** [comment]
why are we buying from a pool when asset's price schema is fixed rate?

**Comment by EnzoVezzaro** [comment]
> why are we buying from a pool when asset's price schema is fixed rate?

Yes. We had an issue with the logic, now should be fine.

**Review by jamiehewitt15 — APPROVED** [review]

File: src/components/Asset/AssetActions/Download.tsx [hunk 1]
```diff
@@ -71,23 +71,29 @@ export default function Download({
...
+
       const orderPriceAndFees = await getOrderPriceAndFees(
         asset,
         ZERO_ADDRESS,
         params
       )
 
       setOrderPriceAndFees(orderPriceAndFees)
-      setIsDisabled(false)
+      if (isAssetNetwork) {
```
Comment (kremalicious) [inline src/components/Asset/AssetActions/Download.tsx:90]: in theory, this makes `isAssetNetwork` a dependency of the effect, just like the removed `isLoading` so should be added to dependency array. That is unless something else in existing dependency would change on wallet network change too, in which case we would know better than ESLint and we should add an ESLint-disabling comment on the dependency array so the warning here doesn't appear:

Screen Shot 2022-04-27 at 21 48 29

File: src/components/Asset/AssetActions/Download.tsx [hunk 2]
```diff
@@ -98,7 +104,9 @@ export default function Download({
 
     const isDisabled =
       !asset?.accessDetails.isPurchasable ||
+      !isAssetNetwork ||
```
Comment (kremalicious) [inline src/components/Asset/AssetActions/Download.tsx:107]: this is such an obvious change and I we just missed that cause it's already in below crazy logic line. Which makes we wonder if we should rather split this up, as on quick look like user could have case where only `! isBalanceSufficient` happens which then would be also missed by below line. Can't remember what exactly the purpose of this line is so least we should do adding code comment describing intention.

File: src/components/Asset/AssetActions/Download.tsx (hunk 1 above)
Comment (kremalicious) [reply src/components/Asset/AssetActions/Download.tsx:90]: another thing, we might not need to call `setIsDisabled()` here based on `isAssetNetwork` as further down in the next effect we only deal with the disable state of the button.

File: src/components/Asset/AssetActions/Compute/index.tsx [hunk 3]
```diff
@@ -420,7 +420,11 @@ export default function Compute({
             assetTimeout={datasetTimeout}
             hasPreviousOrderSelectedComputeAsset={hasPreviousAlgorithmOrder}
             hasDatatokenSelectedComputeAsset={hasAlgoAssetDatatoken}
-            oceanSymbol={accessDetails ? accessDetails.baseToken.symbol : ''}
+            oceanSymbol={
+              accessDetails?.baseToken?.symbol
```
Comment (kremalicious) [inline src/components/Asset/AssetActions/Compute/index.tsx:424]: `accessDetails?.baseToken?.symbol || ''` should be the same, just shorter?

File: src/@utils/accessDetailsAndPricing.ts [hunk 4]
```diff
@@ -256,6 +256,7 @@ export async function getOrderPriceAndFees(
     asset?.services[0].serviceEndpoint
   )
   orderPriceAndFee.providerFee = initializeData.providerFee
+  if (!orderPriceAndFee.providerFee) return
```
Comment (kremalicious) [inline src/@utils/accessDetailsAndPricing.ts:259]: double checking: under what circumstances could this `orderPriceAndFee.providerFee` be `null` or `undefined`? As this line stops all price fetching in case this is not defined. So question is if we should if maybe somewhere the provider owner would have not set it or something. Do we have a default set wherever we get this from which is not  `null` or `undefined`?

Comment (EnzoVezzaro) [reply src/@utils/accessDetailsAndPricing.ts:259]: This is a edge case when the network is slow. It doesn't happen a lot, but basically yesterday I encounter an issue where the query failed (because infura was slow/down, today i haven't had this issue) and this failing call makes [this line](https://github.com/oceanprotocol/market/blob/fix/issue-1356-loader-stuck-button-asset/src/@utils/accessDetailsAndPricing.ts#L289) of code throw an error. To avoid this extremely limited edge case, I added this return when providerFee is null (aka there's an error retrieving the data). We can remove it, if we think this will not create a problem in the future.

File: src/components/Asset/AssetActions/Download.tsx (hunk 1 above)
Comment (EnzoVezzaro) [reply src/components/Asset/AssetActions/Download.tsx:90]: removed both as they're not necessary

File: src/components/Asset/AssetActions/Download.tsx (hunk 2 above)
Comment (EnzoVezzaro) [reply src/components/Asset/AssetActions/Download.tsx:107]: tested all possible combinations, didn't encounter errors. I have left a comment on it, but I'm not sure why [these conditions](https://github.com/oceanprotocol/market/blob/fix/issue-1356-loader-stuck-button-asset/src/components/Asset/AssetActions/Download.tsx#L108) are grouped though.

Comment (kremalicious) [reply src/components/Asset/AssetActions/Download.tsx:113]: awesome, thanks for testing and those code comments are really great. We better not touch the line then if all works 🙃
