### PR TITLE
Fix pagination breaks on to many results

### LINKED ISSUE #719: Pagination breaks if there are too many total results
It's a bug with the es query, it has limitations 10k results. Need to research scroll or search after (maybe wait for es upgrade )

### PR DESCRIPTION
**Pull request by KatunaNorbert**
Fixes #719 .

Changes proposed in this PR:

- Fix pagination breaks on to many results

### CODE REVIEW

File: src/pages/search.tsx [hunk 1]
```diff
@@ -32,10 +33,19 @@ export default function PageGatsbySearch(props: PageProps): ReactElement {
       }`
 
   return (
-    <Page title={title} uri={props.uri}>
+    <Page
+      title={title}
+      description={
+        totalPagesNumber &&
+        totalPagesNumber > 476 &&
+        'More than 10k results were found, displaying the first 10k. Please refine your search'
```
Comment (jamiehewitt15) [inline src/pages/search.tsx:41]: In general, it works very nicely and is a good solution. I think we could refine the message slightly as it says "60876 results for data" and then "More than 10k results were found" which seems like repetition. 

Pagination message

I would suggest a shorter message "Results are limited to the first 10k, please refine your search."

```suggestion
        'Results are limited to the first 10k, please refine your search.'
```

Comment (KatunaNorbert) [reply src/pages/search.tsx:41]: Thanks for the feedback. It might sound a bit repetitive and also not sure if that number '60876'  of results makes any sense in this context.
So the title could be `More than 10k results for data` and in description 'First 10k results are displayed. Please refine your search' or simply 'Please refine your search' for description

Comment (kremalicious) [reply src/pages/search.tsx:41]: agree, if we only display 10000 results then the title should reflect that, maybe `>10000 results for data`. As for the message I'm afraid people will miss it as their eyes most likely will jump to asset list results right away. Not sure how feasible it is to put an `<Alert state="info">` into that `description`, if we markdown-process that already we could at least make it bold with `**Results displayed are limited to the first 10k, please refine your search.**`

Comment (KatunaNorbert) [reply src/pages/search.tsx:41]: showing an `alert` components doesn't seem too feasible without modifying some components because right now it waits for the description as a string. I don't think it's worth modifying it for this scope, because in most of the cases the user will refine the search when he sees this much results.

File: src/components/molecules/PageHeader.tsx [hunk 2]
```diff
@@ -21,7 +22,11 @@ export default function PageHeader({
   return (
     <header className={styleClasses}>
       <h1 className={styles.title}>{title}</h1>
-      {description && <p className={styles.description}>{description}</p>}
+      {description && (
+        <p className={styles.description}>
+          <Markdown text={description} />
```
Comment (kremalicious) [inline src/components/molecules/PageHeader.tsx:27]: This results in invalid markup (can't have `p` add child of `p`):

Screen Shot 2021-09-13 at 15 25 10

So goal here would be to reduce nested markup as much as possible, ideally the `Markdown` component outputs as `p` and gets the `className={styles.description}`

Comment (KatunaNorbert) [reply src/components/molecules/PageHeader.tsx]: oh right, haven't seen that

**Review by kremalicious — APPROVED** [review]

File: src/components/molecules/Pagination.tsx [hunk 3]
```diff
@@ -56,7 +56,7 @@ export default function Pagination({
 
   return totalPageNumbers && totalPageNumbers > 1 ? (
     <ReactPaginate
-      pageCount={totalPageNumbers}
+      pageCount={totalPageNumbers > 476 ? 476 : totalPageNumbers}
```
Comment (bogdanfazakas) [inline src/components/molecules/Pagination.tsx:59]: it would be nice if the 476 value would be wrapped in a constant that we can use across all affected components, so if the maximum result value changes we don't need to find all the 476 values and replace them with the new total page number value and would be easier to understand in a eventual later update

**Review by bogdanfazakas — APPROVED** [review]
Functionality wise all good with the PR, take a look at the previous comment and see if it would be feasible otherwise good to go

File: src/components/molecules/Pagination.tsx (hunk 3 above)
Comment (KatunaNorbert) [reply src/components/molecules/Pagination.tsx:59]: yep this can be done, I think we can add a constant inside aquarius file and import it in those places
