### PR TITLE
Sample file validation in edit form fix

### LINKED ISSUE #1350: Validating file on edit form doesn't work
Screenshot from 2022-04-18 11-14-16

### PR DESCRIPTION
**Pull request by claudiaHash**
Fixes #1350  .

### CODE REVIEW

File: src/components/@shared/FormFields/FilesInput/index.tsx [hunk 1]
```diff
@@ -6,18 +6,22 @@ import { InputProps } from '@shared/FormInput'
...
 
   async function handleValidation(e: React.SyntheticEvent, url: string) {
     // File example 'https://oceanprotocol.com/tech-whitepaper.pdf'
     e.preventDefault()
 
     try {
-      const providerUrl = values?.services[0].providerUrl.url
+      const providerUrl = values?.services
+        ? values?.services[0].providerUrl.url
+        : asset.services[0].serviceEndpoint
```
Comment (mihaisc) [inline src/components/@shared/FormFields/FilesInput/index.tsx:24]: Not sure what to think about this. Considering this component will not be used in other places ... i think it's ok. Refactoring this will take too much time.

**Review by mihaisc — APPROVED** [review]

File: src/components/@shared/FormFields/FilesInput/index.tsx (hunk 1 above)
Comment (bogdanfazakas) [inline src/components/@shared/FormFields/FilesInput/index.tsx:24]: Why don't we keep just `asset?.services?[0]?.serviceEndpoint` since the providerUrl can't be edited ?

Comment (claudiaHash) [reply src/components/@shared/FormFields/FilesInput/index.tsx:24]: not sure bout the implications since this component is used in publish form as well

Comment (bogdanfazakas) [reply src/components/@shared/FormFields/FilesInput/index.tsx:24]: yep nvm them makes sense 😃

**Review by bogdanfazakas — APPROVED** [review]
