### PR TITLE
fixed price and gas estimate

### LINKED ISSUE #144: Fixed price not working
Fixed price is not working due to the refactor of pricing, and the relationship between price and dt minted.

image
Possible solutions: 
- mint maximum amount
- let user input number of dt

### PR DESCRIPTION
**Pull request by mihaisc**
fix fixed price creation
fix gas estimation

closes #144

### CODE REVIEW

File: src/components/organisms/AssetContent/Pricing/FormPricing/index.tsx [hunk 1]
```diff
@@ -35,16 +35,18 @@ export default function FormPricing({
   function handleTabChange(tabName: string) {
     const type = tabName.toLowerCase()
     setFieldValue('type', type)
+    type == 'fixed' && setFieldValue('dtAmount', 1000)
```
Comment (kremalicious) [inline src/components/organisms/AssetContent/Pricing/FormPricing/index.tsx:38]:
```suggestion
    type === 'fixed' && setFieldValue('dtAmount', 1000)
```

**Review by kremalicious — APPROVED** [review]
