### PR TITLE
fix "owned by" label on preview

### LINKED ISSUE #1299: owner doesn't change in Preview
**Describe the bug**
If you are in the Preview step in publish and decides to change account, the owner wallet's information doesn't change in the UI. If you exit and enter back to preview, you'll see the change taking place.

**To Reproduce**
1. Go to Publish
2. Fill out until Preview
3. Change wallet's account
4. See old "Owner" account and "Owned by <old account>"

**Expected behavior**
To change in realtime

**Screenshots**
Screen Shot 2022-04-01 at 7 19 50 AM

### PR DESCRIPTION
**Pull request by EnzoVezzaro**
- Fixes #1299 

Changes proposed in this PR:

- fix "owner by" label on preview
- cleanup - remove unused code

### CODE REVIEW

File: src/components/@shared/Publisher/index.tsx [hunk 1]
```diff
@@ -41,13 +38,6 @@ export default function Publisher({
         setAccountEns(accountEns)
         setName(accountEns)
       }
-
-      // 3box
-      const profile = await get3BoxProfile(account, source.token)
```
Comment (kremalicious) [inline src/components/@shared/Publisher/index.tsx:46]: removing this effectively removes all 3box support for the publisher line, also for those for which it still works. When looking at current live (v3) market, 3box is still working for all the accounts which have highest liquidity assets:

Screen Shot 2022-04-04 at 13 41 14

Migrating 3box to its successor, or something else, should be left for #695 and for now we leave this in place also for publisher line here

Comment (EnzoVezzaro) [reply src/components/@shared/Publisher/index.tsx]: you're right, 3box restored 👍🏽 thanks for that

**Review by mihaisc — APPROVED** [review]
